### ISSUE TITLE
Ability to put javascript variables in data parameter

### ISSUE THREAD

**Issue by varunasingh** [MatchingRadar/Mr.JsonTable#1]
Am I doings something wrong, or I cannot put javascript variables in the main data part of the implementation?

**Comment by MatchingRadar** [comment]
This jquery plug in is to generate a HTML table out of json data. what are you trying to do with javascript variables? Does the variable contain json data?

**Comment by varunasingh** [comment]
yes. I'm getting the JSON data from a url (using Django, but irrelevant) and its a JSON variable.

**Comment by MatchingRadar** [comment]
Is it an array of json data? like
var data = [{ "item": "value"},{ "item": "value" }];
Can you pop on what the data looks like

**Comment by varunasingh** [comment]
That is correct. in that case, data is basically:
var data = " [{'item' : 'value' }, ...
Another example that I'm playing with:

[{"id":"a0a49928-22b0-48a3-88f1-67d9cec63830","verb":"experienced","inProgress":false},{"id":"32a67204-51c0-4fdb-b117-fa513df90ed7","verb":"attempted","inProgress":false}]

So I think data is a string of the json data in the above case. I can do a console.log and it will output it as above.  I want to use that variable in the "data" part of your JSON->HTML TABLE implementation. 

reason why I might want to deal with variables: I might want to play around with the JSON or since I'm working with django, I access the JSON's sub elements in the form of variables for now.. 

Thoughts?

**Comment by MatchingRadar** [comment]
i think it might possibly be the boolean value? Let me do a quick test

**Comment by varunasingh** [comment]
I actually copied the exact value in the variable and pasted in the part after data:
as in:

data: [{"id":"a0a49928-22b0-48a3-88f1-67d9cec63830","verb":"experienced","inProgress":false},{"id":"32a67204-51c0-4fdb-b117-fa513df90ed7","verb":"attempted","inProgress":false}]

and that worked well. 
when I replace the above with:

data: json_data 
(where json_data is a javascript variable), it didn't quite co-operate. So I don't think the Boolean variable is at fault here. 
Have you tried to test it with variables before ?

**Comment by MatchingRadar** [comment]
This works...

<script>
        $(function () {
            var data = [{ "id": "a0a49928-22b0-48a3-88f1-67d9cec63830", "verb": "experienced", "inProgress": false }, { "id": "32a67204-51c0-4fdb-b117-fa513df90ed7", "verb": "attempted", "inProgress": false }];
            $("#mydiv").mrjsontable({
                columns: [
                    new $.fn.mrjsontablecolumn({
                        heading: "ID",
                        data: "id"
                    }),
                    new $.fn.mrjsontablecolumn({
                        heading: "verb",
                        data: "verb"
                    }),
                    new $.fn.mrjsontablecolumn({
                        heading: "inProgress",
                        data: "inProgress"
                    }),
                ],
                data: data
            });
        });
    </script>

**Comment by MatchingRadar** [comment]
```
    $(function () {
        var data = [{ "id": "a0a49928-22b0-48a3-88f1-67d9cec63830", "verb": "experienced", "inProgress": false }, { "id": "32a67204-51c0-4fdb-b117-fa513df90ed7", "verb": "attempted", "inProgress": false }];

        $("#mydiv").mrjsontable({
            columns: [
                new $.fn.mrjsontablecolumn({
                    heading: "ID",
                    data: "id"
                }),
                new $.fn.mrjsontablecolumn({
                    heading: "verb",
                    data: "verb"
                }),
                new $.fn.mrjsontablecolumn({
                    heading: "inProgress",
                    data: "inProgress"
                }),
            ],
            data: data
        });
    });
```

**Comment by MatchingRadar** [comment]
Sorry let me know if I can close this! :dancers:

**Comment by varunasingh** [comment]
Thanks for confirming this, this worked for me. Im working with a bigger JSON set. I think my JSON is passed wrong. Thanks for the time!

**Comment by MatchingRadar** [comment]
No problems. If you need to validate the json copy and paste it into http://jsonformatter.curiousconcept.com/ or http://jsonlint.com/ (jsonlint.com did freeze on me when i put in a massive json object so be warned!)

**Comment by varunasingh** [comment]
So I fixed my problems here and I thought I put them down for anyone who comes here from the interwebs.

When you get your JSON data from django, you need to bind it to a variable and parse it as a JSON. You might need to do first replace the encoded characters (eg: &quot, u&#39) to the actual characters  by javascript replace function. 
After that, you need to parse the javascript as a JSON. eg:

var datad = {{django_data}} //gotten from Django
datad = datad.replace (/u&#39;/g,"\""); (same for $#39 and others)
var data = JSON.parse(datad) 

This data then goes in the Mr.JsonTable data side.
